backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img
media_library:
  name: cloudinary
  config:
    cloud_name: o0o
    api_key: 478312484494422

collections:
  - name: 'posts'
    label: 'Post'
    folder: 'content/posts'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }